// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfr9q5Y0TxDGL4toxlUEZiWaRO7hm8aM0',
    appId: '1:478525793741:web:4e3d9a6a1013bc6cb01084',
    messagingSenderId: '478525793741',
    projectId: 'sais-6168b',
    authDomain: 'sais-6168b.firebaseapp.com',
    storageBucket: 'sais-6168b.firebasestorage.app',
    measurementId: 'G-TG9V6F7MN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOGxcQAZIWFZuJgKoojRR3e7i0C6ioCE',
    appId: '1:478525793741:android:4afa3402f587d749b01084',
    messagingSenderId: '478525793741',
    projectId: 'sais-6168b',
    storageBucket: 'sais-6168b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9HTDSGh8qmadcKiUK35E7afWUWNWjfw',
    appId: '1:478525793741:ios:b7bf4fb4ea1c66acb01084',
    messagingSenderId: '478525793741',
    projectId: 'sais-6168b',
    storageBucket: 'sais-6168b.firebasestorage.app',
    iosBundleId: 'com.example.projectsais',
  );
}
